name: reminder
description: A Flutter application that allows users to set reminders at specific intervals.
version: 1.0.0+1
publish_to: 'none' 

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^16.2.0
  provider: ^6.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/54105876/d0e4c2e0-ed88-4e4d-85c3-3ed29117e46a.png
  #   - assets/54105876/ef45e39f-997e-492b-be57-7aa090d16a05.png